
```{r html, echo=FALSE}
# global chunk options
knitr::opts_chunk$set(fig.align='center', 
                      out.width='80%',
                      comment='#>',
                      collapse=TRUE)

my_output <- knitr::opts_knit$get("rmarkdown.pandoc.to")

escape_latex = function(x, newlines=FALSE, spaces=FALSE) {
    # function for escaping special LaTeX characters
	x = gsub('\\\\', '\\\\textbackslash', x)
	x = gsub('([#$%&_{}])', '\\\\\\1', x)
	x = gsub('\\\\textbackslash', '\\\\textbackslash{}', x)
	x = gsub('~', '\\\\textasciitilde{}', x)
	x = gsub('\\^', '\\\\textasciicircum{}', x)
	if (newlines) x = gsub('(?<!\n)\n(?!\n)', '\\\\\\\\', x, perl=TRUE)
	if (spaces) x = gsub('  ', '\\\\ \\\\ ', x)
	x
}

ttcode <- function(x, type = "tt") {
    # function to format inline code | latex vs html
    outputFormat <- knitr:::pandoc_to()
    if (outputFormat %in% c('latex', 'beamer'))
        paste0("\\texttt{", escape_latex(x), "}")
    else if (outputFormat == 'html')
        paste0("<", type, ">", x, "</", type, ">")
    else
        x
}

```{r latex, eval=knitr::opts_knit$get("rmarkdown.pandoc.to") == "latex", echo=FALSE}
knitr::opts_chunk$set(fig.width=5.6, fig.height=3.7, fig.align='center', fig.pos='h') 
```
